config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show]
  devise_for :user

  resources :counterparties
  resources :groups_counterparties
  resources :goods

  # resources :users do
  #   member do
  #     put 'block', to: 'blockingusers#block'
  #     put 'unblock', to: 'blockingusers#unblock'
  #   end
  #
  #   collection do
  #     get 'search', to: 'search#show'
  #   end
  # end

  namespace :admin do
    resources :users do
      member do
        put 'block', to: 'blockingusers#block'
        put 'unblock', to: 'blockingusers#unblock'
      end
    end
  end

  namespace :profile do
    resources :user, except: [:new, :create]
  end

  root to: "home#index"
end

__END__
# ресурс -> URL -> тип (.mp3 .js .css .html .xml .mp4 .ttf)
  # hypertext transfer protocol
  # http://    mail.ru:  8080   /media/video_234                       .mp4
  # ПРОТОКОЛ - ХОСТ -    ПОРТ - ОТНОСИТЕЛЬНЫЙ АДРЕС РЕСУРСА на хосте - ТИП ресурса
  # sftp://

#  data                         data
#   |                            |
#  ftp          spy             ftp
#   |____________|_______________|
#   |                            |
#  ssh                          ssh
#   |____________________________|
#   |                            |
#  tcp/ip                      tcp/ip
#   |____________________________|


  #HTTP specification
  # GET PUT POST DELETE OPTION

  # список ресурсов данного вида            -> index GET
  # конкретный ресурс                       -> show  GET
  # создать ресурс  POST           (create) -> new   GET
  # изменить ресурс PUT            (update) -> edit  GET
  # удалить ресурс  DELETE         (destroy)

app/models/counterparty.rb
class Counterparty < ApplicationRecord
  belongs_to :groups_counterparty
  validates :name, :groups_counterparty_id, presence: true
  self.per_page = 5
end

app/controllers/counterparties_controller.rb
class CounterpartiesController < ApplicationController
  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @counterparties = Counterparty.order(:name).paginate(:page => params[:page])
  end

  def show
  end

  def new
    @counterparty = Counterparty.new
  end

  def create
    @counterparty = Counterparty.new counterparty_params
    if @counterparty.save
      redirect_to counterparties_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @counterparty.update counterparty_params
      redirect_to counterparties_url
    else
      render :edit
    end
  end

  def destroy
    @counterparty.destroy
    redirect_to counterparties_url
  end

  private

  def counterparty_params
    params.require(:counterparty).permit(:name, :comment, :groups_counterparty_id)
  end

  def load_model
    @counterparty = Counterparty.find params[:id]
  end
end

app/helpers/counterparties_helper.rb
module CounterpartiesHelper
end

app/views/counterparties/_counterparty.html.erb
<tbody>
<% @counterparties.each_with_index do |сounterparty, index| %>
    <tr>
      <td class="td-18 td-right"><%= index + 1 %></td>
      <td class="td-18"><%= link_to icon('fa-edit', 'редактировать'), edit_counterparty_path(сounterparty.id) %></td>
      <td class="td-18 td-right"><%= сounterparty.id %></td>
      <td><%= link_to сounterparty.name, counterparty_path(сounterparty) %></td>
      <td><%= truncate сounterparty.comment %></td>
      <td><%= сounterparty.groups_counterparty.name %></td>
      <td class="td-18"><%= link_to icon('fa-trash', 'удалить'), counterparty_path(сounterparty),
                                    method: :delete, data: {confirm: 'Действительно удалить?'} %></td>
    </tr>
<% end %>
</tbody>

app/views/counterparties/_form.html.erb
<%= simple_form_for @counterparty do |f| %>
    <%= f.input :name, autofocus: true, label: 'Название' %>
    <%= f.collection_select :groups_counterparty_id,  GroupsCounterparty.all, :id, :name, { prompt: "Выбирите группу" }  %>
    <%= f.input :comment, placeholder: 'Текст', label: 'Описание' %>
    <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Отменить', counterparties_path, class: 'btn btn-default' %>
<% end %>

app/views/counterparties/_thead.html.erb
<thead>
<tr>
  <th>№</th>
  <th></th>
  <th>ID</th>
  <th>Название</th>
  <th>Описание</th>
  <th>Группа</th>
  <th></th>
</tr>
</thead>

app/views/counterparties/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Редактировать контрагента</h1>

    <%= render 'counterparties/form' %>
  </div>
</div>

app/views/counterparties/index.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>Контрагенты (<%= render html: @counterparties.count %>)</h1>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <%= link_to 'Новый', new_counterparty_path, class: 'btn btn-primary btn-sm mg-top-24' %>
    </div>
  </div>
</div>
<%= will_paginate @counterparties, renderer: BootstrapPagination::Rails %>
<table class="table table-bordered table-hover">
  <%= render 'counterparties/thead' %>
  <%= render 'counterparties/counterparty' %>
</table>
<%= will_paginate @counterparties, renderer: BootstrapPagination::Rails %>

app/views/counterparties/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Новый контрагент</h1>

    <%= render 'counterparties/form' %>
  </div>
</div>

app/views/counterparties/show.html.erb
<h1><%= @counterparty.name %></h1>
<span>Группа: </span><em><%= @counterparty.groups_counterparty.name %></em>
<p>
  <%= @counterparty.comment %>
</p>
<p>
  <%= link_to 'Вернуться к списку', counterparties_path, class: 'btn btn-default' %>
</p>