config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show]
  devise_for :user

  resources :counterparties
  resources :groups_counterparties
  resources :goods

  # resources :users do
  #   member do
  #     put 'block', to: 'blockingusers#block'
  #     put 'unblock', to: 'blockingusers#unblock'
  #   end
  #
  #   collection do
  #     get 'search', to: 'search#show'
  #   end
  # end

  namespace :admin do
    resources :users do
      member do
        put 'block', to: 'blockingusers#block'
        put 'unblock', to: 'blockingusers#unblock'
      end
    end
  end

  namespace :profile do
    resources :user, except: [:new, :create]
  end

  root to: "home#index"
end

__END__
# ресурс -> URL -> тип (.mp3 .js .css .html .xml .mp4 .ttf)
  # hypertext transfer protocol
  # http://    mail.ru:  8080   /media/video_234                       .mp4
  # ПРОТОКОЛ - ХОСТ -    ПОРТ - ОТНОСИТЕЛЬНЫЙ АДРЕС РЕСУРСА на хосте - ТИП ресурса
  # sftp://

#  data                         data
#   |                            |
#  ftp          spy             ftp
#   |____________|_______________|
#   |                            |
#  ssh                          ssh
#   |____________________________|
#   |                            |
#  tcp/ip                      tcp/ip
#   |____________________________|


  #HTTP specification
  # GET PUT POST DELETE OPTION

  # список ресурсов данного вида            -> index GET
  # конкретный ресурс                       -> show  GET
  # создать ресурс  POST           (create) -> new   GET
  # изменить ресурс PUT            (update) -> edit  GET
  # удалить ресурс  DELETE         (destroy)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/counterparty.rb
class Counterparty < ApplicationRecord
  belongs_to :groups_counterparty
  validates :name, :groups_counterparty_id, presence: true
  self.per_page = 5
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :pictures, as: :imageable
  
  validates :name, presence: true

  accepts_nested_attributes_for :pictures

  # price
  self.per_page = 5
end
#
# Thing -> ThingItem
#
# Pricelist - PricelistItem
# дата        price_list_id, good_id, price, currency
# номер
# город
#
# Order -         OrderItem
# order_date    1, Чайник,   2шт, 300р, 600р
#               2, Кофейник, 1шт, 500р, 500р

app/models/groups_counterparty.rb
class GroupsCounterparty < ApplicationRecord
  has_many :counterparties, dependent: :destroy
  validates :name, presence: true
  self.per_page = 5
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :imageable
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  has_many :pricelist_items
  belongs_to :city
end

app/models/pricelist_item.rb
class PricelistItem < ApplicationRecord
  belongs_to :pricelist
  belongs_to :good

  validates :price, :currency, presence: { message: 'Вы обязательно должны заполнить'}
  validates :price,  numericality: { greater_than_or_equal_to: 0, message: 'обязательно число и не меньше нуля' }
  validates :good_id, uniqueness: { scope: :pricelist_id,
                                 message: "should happen once per good" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  validates :username, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  self.per_page = 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/blockingusers_controller.rb
class BlockingusersController < ApplicationController
  before_action :set_user

  def block
    if @user.update block: true
      flash[:success] = 'Пользователь заблокирован'
    else
      flash[:error] = 'Не удалось заблокировать пользователя'
    end
    redirect_to users_path
  end

  def unblock
    @user.update block: false
    flash[:success] = 'Пользователь разблокирован'
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find params[:id]
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @goods = Good.order(:name).paginate(:page => params[:page])
  end

  def show
  end

  def new
    @good = Good.new
    @good.pictures.build
  end

  def create
    @good = Good.new good_params
    if @good.save
      redirect_to goods_url
    else
      render :new
    end
  end

  def edit
    @good.pictures.build
  end

  def update
    if @good.update good_params
      redirect_to goods_url
    else
      render :edit
    end
  end

  def destroy
    @good.destroy
    redirect_to goods_url
  end

  private

  def good_params
    params.require(:good).permit(:name, :comment, pictures_attributes: [:image])
  end

  def load_model
    @good = Good.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    if @user
      redirect_to user_path(@user)
    else
      flash[:danger] = "Такого пользователя не существует"
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_model, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email).paginate(:page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to users_path, success: 'пользователь обновлен'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def load_model
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(classes, title = nil, style = nil)
    content_tag(:i, '', class: "fa #{classes}", title: title, style: style)
  end

  def noty_type(name)
    name == 'notice' ? 'success' : 'error'
  end
end

app/helpers/blockingusers_helper.rb
module BlockingusersHelper
end

app/helpers/counterparties_helper.rb
module CounterpartiesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/groups_counterparties_helper.rb
module GroupsCounterpartiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goods/_form.html.erb
<%= simple_form_for @good do |f| %>
    <%= f.input :name, autofocus: true, label: 'Название' %>
    <%= f.input :comment, placeholder: 'Текст', label: 'Описание' %>
<p>Картинка:</p>
    <%= f.simple_fields_for :pictures do |p| %>
        <%= p.input :image %>
        <% end %>
    <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Отменить', goods_path, class: 'btn btn-default' %>
<% end %>

app/views/goods/_good.html.erb
<tbody>
<% @goods.each_with_index do |good, index| %>
    <tr>
      <td class="td-18 td-right"><%= index + 1 %></td>
      <td class="td-18 ">
        <% good.pictures.each do |pic| %>
          <%= link_to icon('fa-picture-o', 'Клацни!'), good_path(good), class: 'go', data: { goid: pic.id } %>
          <%#= pic.image.file.filename %>
            <%= render 'goods/modal_image', pic: pic %>
        <% end %>
      </td>

      <td class="td-18"><%= link_to icon('fa-edit', 'редактировать'), edit_good_path(good) %></td>
      <td class="td-18 td-right"><%= good.id %></td>
      <td><%= link_to good.name, good_path(good) %></td>
      <td><%= truncate good.comment %></td>
      <td class="td-18"><%= link_to icon('fa-trash', 'удалить'), good_path(good),
                                    method: :delete, data: {confirm: 'Действительно удалить?'} %></td>
    </tr>
<% end %>
</tbody>

app/views/goods/_modal_image.html.erb
<div class='modal_form' id="modal_form_<%= pic.id %>"><!-- Сaмo oкнo -->
  <span id="modal_close">X</span> <!-- Кнoпкa зaкрыть -->
  <%= image_tag(pic.image.url(:intermedia)) %>
</div>
<div id="overlay"></div><!-- Пoдлoжкa -->

app/views/goods/_thead.html.erb
<thead>
<tr>
  <th>№</th>
  <th></th>
  <th></th>
  <th>ID</th>
  <th>Название</th>
  <th>Описание</th>
  <th></th>
</tr>
</thead>

app/views/goods/edit.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Редактировать товар</h1>

    <%= render 'goods/form' %>
  </div>
</div>

app/views/goods/index.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>Номенклатура (<%= @goods.count %>)</h1>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <%= link_to 'Новый', new_good_path, class: 'btn btn-primary btn-sm mg-top-24' %>
    </div>
  </div>
</div>
<%= will_paginate @goods, renderer: BootstrapPagination::Rails %>
<table class="table table-bordered table-hover">
  <%= render 'goods/thead' %>
  <%= render 'goods/good' %>
</table>
<%= will_paginate @goods, renderer: BootstrapPagination::Rails %>

app/views/goods/new.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">

    <h1>Новый товар</h1>

    <%= render 'goods/form' %>
  </div>
</div>

app/views/goods/show.html.erb
<h1><%= @good.name %></h1>

  <ul class="img">
    <% @good.pictures.each do |pic| %>
        <li><%= link_to image_tag(pic.image.url(:intermedia)), pic.image.url %></li>
        <%#= pic.image.file.filename %>
    <% end %>
  </ul>
<div class="clear"></div>
<p>
  <%= @good.comment %>
</p>
<p>
  <%= link_to 'Вернуться к списку', goods_path, class: 'btn btn-default' %>
</p>